[project]
name = "data-engineer-agent"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
    "rich==14.1.0",
    "fastmcp==2.11.3",
    "awswrangler==3.12.1",
    "strands-agents==1.7.0",
    "strands-agents-tools==0.2.5",
    "dynaconf==3.2.11",
]