name: build-flow 

on: [push]

jobs:
  deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
          version: "0.8.14"
    - uses: actions/checkout@v4
    - name: Restore uv cache
      uses: actions/cache/restore@v4
      with:
        path: ~/.cache/uv
        key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
    
    - name: Install dependencies
      run: |
        uv sync --frozen
    - name: Save uv cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: ~/.cache/uv
        key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
  pylint:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - name: Analysing the code with pylint
        run: |
          uv run pylint $(git ls-files './dea/*.py')
